work in progress on scc initiator

diff --git a/tasks/scc-initiator.yaml b/tasks/scc-initiator.yaml
--- a/tasks/scc-initiator.yaml
+++ b/tasks/scc-initiator.yaml
@@ -53,7 +53,7 @@ spec:
           echo "IAM_TOKEN: ${IAM_TOKEN}"
 
 
-          curl -v \
+          status=$(curl -s -o response.txt -w "%{http_code}" \
             -X POST  "https://${LOCATION}.compliance.cloud.ibm.com/posture/v1/scans/validations?account_id=${ACCOUNT_ID}"   \
             -H 'Authorization: Bearer ${IAM_TOKEN}'   \
             -H 'Content-type: application/json'   \
@@ -61,5 +61,13 @@ spec:
               "scope_id": "${SCOPE_ID}", 
               "profile_id": "${PROFILE_ID}", 
               "group_profile_id": "${GROUP_PROFILE_ID}" 
-            }'
+            }')
+
+          cat response.txt   
+          if [ $status != "200" ]; then
+            #if not http 200, fail the pipeline
+            exit 1
+          else
+            exit 0
+          fi
   
